// Form field config per master table (API table key).
// optionsTable = API table key to fetch dropdown options (e.g. 'continents').

export const entityFields = {
  continents: [
    { name: 'name', label: 'Continent', type: 'text', tableHeader: 'Continent' },
  ],
  countries: [
    { name: 'name', label: 'Country', type: 'text', tableHeader: 'Country' },
    { name: 'continent_id', label: 'Select Continent', type: 'select', optionsTable: 'continents', tableHeader: 'Continent' },
  ],
  'country-divisions': [
    { name: 'name', label: 'Country Division', type: 'text', tableHeader: 'Country Division' },
    { name: 'country_id', label: 'Select Country', type: 'select', optionsTable: 'countries', tableHeader: 'Country' },
  ],
  states: [
    { name: 'name', label: 'State', type: 'text', tableHeader: 'State' },
    { name: 'country_division_id', label: 'Select Country Division', type: 'select', optionsTable: 'country-divisions', tableHeader: 'Country Division' },
  ],
  'state-circles': [
    { name: 'name', label: 'State Circle', type: 'text', tableHeader: 'State Circle' },
    { name: 'state_id', label: 'Select State', type: 'select', optionsTable: 'states', tableHeader: 'State' },
  ],
  'state-divisions': [
    { name: 'name', label: 'State Division', type: 'text', tableHeader: 'State Division' },
    { name: 'state_circle_id', label: 'Select State Circle', type: 'select', optionsTable: 'state-circles', tableHeader: 'State Circle' },
  ],
  'state-sub-divisions': [
    { name: 'name', label: 'State Sub Division', type: 'text', tableHeader: 'State Sub Division' },
    { name: 'state_division_id', label: 'State Division', type: 'select', optionsTable: 'state-divisions', tableHeader: 'State Division' },
  ],
  regions: [
    { name: 'name', label: 'Region', type: 'text', tableHeader: 'Region' },
    { name: 'state_sub_division_id', label: 'Select State Sub Division', type: 'select', optionsTable: 'state-sub-divisions', tableHeader: 'State Sub Division' },
  ],
  zones: [
    { name: 'name', label: 'Zone', type: 'text', tableHeader: 'Zone' },
    { name: 'region_id', label: 'Select Region', type: 'select', optionsTable: 'regions', tableHeader: 'Region' },
  ],
  'vidhan-sabhas': [
    { name: 'name', label: 'Vidhan Sabha', type: 'text', tableHeader: 'Vidhan Sabha' },
    { name: 'vidhan_sabha_type', label: 'Vidhan Sabha types', type: 'select', optionStatic: ['Ruler', 'Arbun'], tableHeader: 'Vidhan Sabha types', optionPlaceholder: 'Select Vidhan Sabha type' },
    { name: 'zone_id', label: 'Select Zone', type: 'select', optionsTable: 'zones', tableHeader: 'Zone' },
  ],
  talukas: [
    { name: 'name', label: 'Taluka', type: 'text', tableHeader: 'Taluka' },
    { name: 'vidhan_sabha_id', label: 'Select Vidhan Sabha', type: 'select', optionsTable: 'vidhan-sabhas', tableHeader: 'Vidhan Sabha' },
  ],
  blocks: [
    { name: 'name', label: 'Block', type: 'text', tableHeader: 'Block' },
    { name: 'taluka_id', label: 'Select Taluka', type: 'select', optionsTable: 'talukas', tableHeader: 'Taluka' },
  ],
  circles: [
    { name: 'name', label: 'Panchayat Samiti Circle', type: 'text', tableHeader: 'Panchayat Samiti Circle' },
    { name: 'block_id', label: 'Select Block', type: 'select', optionsTable: 'blocks', tableHeader: 'Block' },
  ],
  'gram-panchayats': [
    { name: 'name', label: 'Gram Panchayat', type: 'text', tableHeader: 'Gram Panchayat' },
    { name: 'circle_id', label: 'Select Panchayat Samiti Circle', type: 'select', optionsTable: 'circles', tableHeader: 'Panchayat Samiti Circle' },
  ],
  villages: [
    { name: 'name', label: 'Village', type: 'text', tableHeader: 'Village' },
    { name: 'gram_panchayat_id', label: 'Select Gram Panchayat', type: 'select', optionsTable: 'gram-panchayats', tableHeader: 'Gram Panchayat' },
  ],
  products: [
    { name: 'name', label: 'Product', type: 'text', tableHeader: 'Product' },
    {
      name: 'business_sub_category_id',
      label: 'Business Sub Category',
      type: 'select',
      optionsTable: 'business-sub-categories',
      tableHeader: 'Business Sub Category',
    },
  ],
  'business-types': [
    { name: 'name', label: 'Business Type', type: 'text', tableHeader: 'Business Type' },
    {
      name: 'product_id',
      label: 'Select Product',
      type: 'select',
      optionsTable: 'products',
      tableHeader: 'Product',
    },
  ],
  units: [
    { name: 'name', label: 'Unit', type: 'text', tableHeader: 'Unit' },
    { name: 'village_id', label: 'Select Village', type: 'select', optionsTable: 'villages', tableHeader: 'Village' },
    { name: 'unit_type_id', label: 'Select Types of Units', type: 'select', optionsTable: 'unit-types', tableHeader: 'Types of Units' },
    { name: 'status', label: 'Status', type: 'radio', options: ['Active', 'Inactive', 'In progress'], tableHeader: 'Status' },
  ],
  'unit-types': [
    { name: 'type_category', label: 'Type', type: 'selectWithOther', optionsTable: 'unit-types', optionValue: 'type_category', optionLabel: 'type_category', tableHeader: 'Types of Units', optionStatic: ['PNG', 'GLG', 'LLP', 'Pvt', 'SPV', 'LTP'] },
  ],
  'business-categories': [
    { name: 'name', label: 'Business Category', type: 'text', tableHeader: 'Business Category' },
    {
      name: 'vidhan_sabha_id',
      label: 'Select Vidhansabha',
      type: 'select',
      optionsTable: 'vidhan-sabhas',
      tableHeader: 'Vidhansabha',
    },
  ],
  'business-sub-categories': [
    { name: 'name', label: 'Business Sub Category', type: 'text', tableHeader: 'Business Sub Category' },
    {
      name: 'business_category_id',
      label: 'Select Business Category',
      type: 'select',
      optionsTable: 'business-categories',
      tableHeader: 'Business Category',
    },
  ],
  designations: [
    { name: 'name', label: 'Designation', type: 'text', tableHeader: 'Designation' },
    { name: 'parent_id', label: 'No Parent (Top Level)', type: 'select', optionsTable: 'designations', tableHeader: 'Parent', required: false, optionPlaceholder: 'No Parent (Top Level)', optionValue: 'id', optionLabel: 'name' },
  ],
  'business-positions': [
    { name: 'name', label: 'Business Position', type: 'text', tableHeader: 'Business Position' },
    { name: 'code', label: 'Code', type: 'text', tableHeader: 'Code' },
  ],
  'business-sectors': [
    { name: 'name', label: 'Business Sector', type: 'text', tableHeader: 'Business Sector' },
    { name: 'code', label: 'Code', type: 'text', tableHeader: 'Code' },
  ],
  'position-allotments': [
    // User appears last; level is still auto-calculated internally from location
    { name: 'zone_id', label: 'Zone', type: 'select', optionsTable: 'zones', tableHeader: 'Zone', optionPlaceholder: 'Select Zone' },
    { name: 'vidhan_sabha_id', label: 'Vidhan Sabha', type: 'select', optionsTable: 'vidhan-sabhas', tableHeader: 'Vidhan Sabha', optionPlaceholder: 'Select Vidhan Sabha' },
    { name: 'taluka_id', label: 'Taluka', type: 'select', optionsTable: 'talukas', tableHeader: 'Taluka', optionPlaceholder: 'Select Taluka' },
    { name: 'block_id', label: 'Block', type: 'select', optionsTable: 'blocks', tableHeader: 'Block', optionPlaceholder: 'Select Block' },
    { name: 'circle_id', label: 'Panchayat Samiti Circle', type: 'select', optionsTable: 'circles', tableHeader: 'Panchayat Samiti Circle', optionPlaceholder: 'Select Circle' },
    { name: 'gram_panchayat_id', label: 'Gram Panchayat', type: 'select', optionsTable: 'gram-panchayats', tableHeader: 'Gram Panchayat', optionPlaceholder: 'Select Gram Panchayat' },
    { name: 'village_id', label: 'Village', type: 'select', optionsTable: 'villages', tableHeader: 'Village', optionPlaceholder: 'Select Village' },
    { name: 'business_position_id', label: 'Business Position', type: 'select', optionsTable: 'designations', tableHeader: 'Business Position', optionPlaceholder: 'Select Position' },
    { name: 'business_category_id', label: 'Business Sector', type: 'select', optionsTable: 'business-categories', tableHeader: 'Business Sector', optionPlaceholder: 'Select Business Sector' },
    { name: 'user_name', label: 'User Name', type: 'select', optionsTable: 'management-registrations', optionValue: 'name', optionLabel: 'name', tableHeader: 'User Name', optionPlaceholder: 'Select User' },
  ],
  'business-unit-allotments': [
    { name: 'business_category_id', label: 'Business Category', type: 'select', optionsTable: 'business-categories', tableHeader: 'Business Category', optionPlaceholder: 'Select Business Category' },
    { name: 'business_sub_category_id', label: 'Business Sub Category', type: 'select', optionsTable: 'business-sub-categories', tableHeader: 'Business Sub Category', optionPlaceholder: 'Select Business Sub Category' },
    { name: 'product_id', label: 'Product', type: 'select', optionsTable: 'products', tableHeader: 'Product', optionPlaceholder: 'Select Product' },
    { name: 'business_type_id', label: 'Type of Business', type: 'select', optionsTable: 'business-types', tableHeader: 'Type of Business', optionPlaceholder: 'Select Type of Business' },
    { name: 'unit_type_id', label: 'Type of Unit / Company', type: 'select', optionsTable: 'unit-types', tableHeader: 'Type of Unit / Company', optionPlaceholder: 'Select Type of Unit / Company' },
    { name: 'business_cluster_name', label: 'Business Cluster Name', type: 'text', tableHeader: 'Business Cluster Name' },
    { name: 'unit_company_name', label: 'Unit / Company Name', type: 'text', tableHeader: 'Unit / Company Name' },
    { name: 'beneficiary_name', label: 'Name of Beneficiary', type: 'text', tableHeader: 'Name of Beneficiary' },
    { name: 'aadhar_card_number', label: 'Aadhaar Card Number', type: 'text', numericOnly: true, tableHeader: 'Aadhaar Card Number' },
    { name: 'pan_card_number', label: 'PAN Card Number', type: 'text', tableHeader: 'PAN Card Number' },
    { name: 'shg_membership_certificate', label: 'SHG Membership Certificate (Yes/No)', type: 'select', optionStatic: ['YES', 'NO'], tableHeader: 'SHG Membership Certificate' },
    { name: 'shg_membership_certificate_file', label: 'SHG Membership Certificate File', type: 'file', tableHeader: 'SHG Membership Certificate File' },
    { name: 'small_landholder_certificate', label: 'Minority / Small / Landholder / Forest Rights Holder Certificate (Yes/No)', type: 'select', optionStatic: ['YES', 'NO'], tableHeader: 'Small / Landholder / Forest Rights Holder' },
    { name: 'small_landholder_certificate_file', label: 'Minority / Small / Landholder / Forest Rights Holder Certificate File', type: 'file', tableHeader: 'Small / Landholder / Forest Rights Holder File' },
    { name: 'caste_certificate_scst', label: 'Caste Certificate for Scheduled Caste / Tribe (Yes/No)', type: 'select', optionStatic: ['YES', 'NO'], tableHeader: 'Caste Certificate SC/ST' },
    { name: 'caste_certificate_scst_file', label: 'Caste Certificate for Scheduled Caste / Tribe File', type: 'file', tableHeader: 'Caste Certificate SC/ST File' },
    { name: 'special_category_certificate', label: 'Special Category Certificate (Yes/No)', type: 'select', optionStatic: ['YES', 'NO'], tableHeader: 'Special Category Certificate' },
    { name: 'special_category_certificate_file', label: 'Special Category Certificate File', type: 'file', tableHeader: 'Special Category Certificate File' },
    { name: 'udid_disability_certificate', label: 'UDID Certificate for Disability Beneficiary (Yes/No)', type: 'select', optionStatic: ['YES', 'NO'], tableHeader: 'UDID Certificate' },
    { name: 'udid_disability_certificate_file', label: 'UDID Certificate File', type: 'file', tableHeader: 'UDID Certificate File' },
    { name: 'training_certificate_file', label: 'Training Certificate of Govt / Semi-Govt Organization', type: 'file', tableHeader: 'Training Certificate' },
    { name: 'educational_marks_sheet_file', label: 'Educational Marks Sheet Certificate', type: 'file', tableHeader: 'Educational Marks Sheet' },
    { name: 'school_leaving_certificate_file', label: 'School Leaving Certificate (TC)', type: 'file', tableHeader: 'School Leaving Certificate' },
    { name: 'birth_certificate_file', label: 'Birth Certificate', type: 'file', tableHeader: 'Birth Certificate' },
    { name: 'domicile_nationality_certificate_file', label: 'Domicile / Nationality Certificate', type: 'file', tableHeader: 'Domicile / Nationality Certificate' },
    { name: 'cibil_report_score', label: 'CIBIL Report Score', type: 'text', numericOnly: true, tableHeader: 'CIBIL Report Score' },
    { name: 'bank_name', label: 'BANK NAME', type: 'text', tableHeader: 'Bank Name' },
    { name: 'bank_branch_city', label: 'BANK BRANCH: GAON / CITY', type: 'text', tableHeader: 'Bank Branch: Gaon/City' },
    { name: 'bank_branch_taluka', label: 'BANK BRANCH: TALUKA', type: 'text', tableHeader: 'Bank Branch: Taluka' },
    { name: 'bank_branch_district', label: 'BANK BRANCH: DISTRICT', type: 'text', tableHeader: 'Bank Branch: District' },
    { name: 'bank_branch_state', label: 'BANK BRANCH: STATE', type: 'text', tableHeader: 'Bank Branch: State' },
    { name: 'bank_branch_manager_name', label: "BANK BRANCH MANAGER'S NAME", type: 'text', tableHeader: "Branch Manager's Name" },
    { name: 'bank_branch_manager_mobile', label: "BANK BRANCH MANAGER'S MOBILE NUMBER", type: 'text', numericOnly: true, tableHeader: "Branch Manager's Mobile" },
    { name: 'bank_branch_ifsc_code', label: 'BANK BRANCH IFSC CODE', type: 'text', tableHeader: 'IFSC Code' },
    { name: 'bank_current_account_cancelled_cheque_file', label: 'BANK CURRENT ACCOUNT NUMBER (UPLOAD CANCELLED CHEQUE)', type: 'file', tableHeader: 'Current Account (Cancelled Cheque)' },
    { name: 'bank_saving_account_passbook_first_page_file', label: 'BANK SAVING ACCOUNT NUMBER (UPLOAD PASSBOOK FIRST PAGE)', type: 'file', tableHeader: 'Saving Account (Passbook First Page)' },
    { name: 'land_plot_finalized_30_years', label: 'LAND / PLOT FINALIZED AND REGISTERED FOR 30 YEARS (YES/NO)', type: 'select', optionStatic: ['YES', 'NO'], tableHeader: 'Land/Plot Finalized 30 Years' },
    { name: 'land_plot_finalized_30_years_file', label: 'LAND / PLOT FINALIZED (UPLOAD FILE)', type: 'file', tableHeader: 'Land/Plot Finalized File' },
    { name: 'land_owner_name', label: 'LAND OWNER NAME', type: 'text', tableHeader: 'Land Owner Name' },
    { name: 'land_owner_mobile', label: 'LAND OWNER MOBILE NUMBER', type: 'text', numericOnly: true, tableHeader: 'Land Owner Mobile' },
    { name: 'land_address_gis', label: 'ADDRESS ALONG WITH MAP (GIS)', type: 'text', tableHeader: 'Address (GIS)' },
    { name: 'land_current_location', label: 'CURRENT LOCATION', type: 'text', tableHeader: 'Current Location' },
    { name: 'land_gis_map_file', label: 'MAP (GIS) FILE (UPLOAD)', type: 'file', tableHeader: 'GIS Map File' },
    { name: 'land_7_12_8a_papers_file', label: '7/12 & 8A PAPERS OF LAND (UPLOAD)', type: 'file', tableHeader: '7/12 & 8A Papers' },
    { name: 'land_other_rights_j_certificate_file', label: '“Other rights” entry / “J” certificate (UPLOAD)', type: 'file', tableHeader: 'Other rights / J certificate' },
    { name: 'udyami_certificate', label: 'UDYAMI CERTIFICATE (YES/NO)', type: 'select', optionStatic: ['YES', 'NO'], tableHeader: 'UDYAMI Certificate (Yes/No)' },
    { name: 'udyami_certificate_file', label: 'UDYAMI CERTIFICATE (UPLOAD)', type: 'file', tableHeader: 'UDYAMI Certificate File' },
    { name: 'shop_act_gumasta_license_file', label: 'SHOP ACT / GUMASTA LICENSE (UPLOAD)', type: 'file', tableHeader: 'Shop Act / Gumasta License' },
    { name: 'fssai_certificate_file', label: 'FSSAI CERTIFICATE (UPLOAD)', type: 'file', tableHeader: 'FSSAI Certificate' },
    { name: 'gst_certificate_file', label: 'GST CERTIFICATE (UPLOAD)', type: 'file', tableHeader: 'GST Certificate' },
    { name: 'pf_esic_tan_certificate_file', label: 'PF / ESIC / TAN CERTIFICATE (UPLOAD)', type: 'file', tableHeader: 'PF/ESIC/TAN Certificate' },
    { name: 'factory_license_file', label: 'FACTORY LICENSE (UPLOAD)', type: 'file', tableHeader: 'Factory License' },
    { name: 'pollution_certificate_file', label: 'POLLUTION CERTIFICATE (UPLOAD)', type: 'file', tableHeader: 'Pollution Certificate' },
    { name: 'bank_fin_undertaking_form_file', label: 'UNDERTAKING FORM.. 1 MB (AS PER CMEGP SCHEME) (UPLOAD)', type: 'file', tableHeader: 'Undertaking Form (CMEGP)' },
    { name: 'bank_fin_dpr_file', label: 'DETAILED PROJECT REPORT (DPR) ..1 MB (UPLOAD)', type: 'file', tableHeader: 'DPR' },
    { name: 'bank_fin_quotation_machinery_file', label: 'QUOTATION (MACHINERY & ANCILLIARY EQUIPMENTS, ELECTRICAL, MECHANICAL ETC) (UPLOAD)', type: 'file', tableHeader: 'Quotation - Machinery/Equipment' },
    { name: 'bank_fin_quotation_boundary_wall_file', label: 'QUOTATION (BOUNDARY WALL , CONSTRUCTION/ SHED ) (UPLOAD)', type: 'file', tableHeader: 'Quotation - Boundary Wall / Shed' },
    { name: 'bank_fin_tie_up_agreement_file', label: 'TIE UP AGREEMENT BETWEEN GAON MAJHA UDYOG FOUNDATION & BENEFICIARY FOR 30 YEARS (UPLOAD)', type: 'file', tableHeader: 'Tie-up Agreement (30 years)' },
    { name: 'bank_fin_loan_sanction_letter_file', label: 'BANK LOAN SANCTION LETTER (UPLOAD)', type: 'file', tableHeader: 'Bank Loan Sanction Letter' },
  ],
};
